services:
  auditingrecordapp:
    image: auditingrecordapp
    container_name: auditing-record-app
    build:
      context: .
      dockerfile: AuditingRecordApp/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    depends_on:
      - auditingrecordapp-db
    ports:
     - 8080:8080
     - 8081:8081
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  auditingrecordapp-db:
      image: postgres:latest
      container_name: AuditingRecordApp-db
      environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
        - POSTGRES_INITDB_ARGS=--auth-host=trust
        - POSTGRES_DB=AuditingRecordApp
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Sou@2345
      volumes:
        - db_volume:/var/lib/postgresql/data
      ports:
        - 5432:5432

volumes:
  db_volume:
